version: '4'
services:
  ionic:
    image: abusubha/photogallery
    volumes:
      - .:/www/app
    working_dir: /www/app
    ports:
     - "8100:8100"
    command: ["serve", "--external", "--no-open"]
    
