FROM node:14.17

ARG WORK_DIR=/ionicApp
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

RUN mkdir ${WORK_DIR}
WORKDIR ${WORK_DIR}

COPY package.json ${WORK_DIR}
COPY package-lock.json ${WORK_DIR}

RUN npm install @angular/cli
RUN npm install @ionic/cli
RUN npm install

COPY . ${WORK_DIR}

EXPOSE 8100

ENTRYPOINT ["npm"]
CMD ["run", "start"]

# /app/www/ /usr/share/nginx/html/